/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Class.koneksi;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class frm_laporan extends javax.swing.JFrame {
        private Connection con = koneksi.getConnection();
    private Statement stt;
    private ResultSet rss;

    /**
     * Creates new form frm_laporan
     */
    public void CetakLaporan (String NamaFile, HashMap hash){
        try{
            InputStream report;
            report = getClass().getResourceAsStream(NamaFile);
            JasperPrint jprint = JasperFillManager.fillReport (report, hash, con);
                JasperViewer viewer = new JasperViewer (jprint, false);
                viewer.setFitPageZoomRatio();
                viewer.setVisible(true);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }        
    }
    
    public frm_laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        jButton1 = new javax.swing.JButton();
        panel2 = new usu.widget.Panel();
        btnPenghuni = new javax.swing.JButton();
        btnKamar = new javax.swing.JButton();
        btnFasilitas = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        panel2.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/IMG/bgFormLaporan.png"))); // NOI18N
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPenghuni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPenghuni.setText("Cetak");
        btnPenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenghuniActionPerformed(evt);
            }
        });
        panel2.add(btnPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 149, 80, 30));

        btnKamar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKamar.setText("Cetak");
        btnKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarActionPerformed(evt);
            }
        });
        panel2.add(btnKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 215, 80, 30));

        btnFasilitas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFasilitas.setText("Cetak");
        btnFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFasilitasActionPerformed(evt);
            }
        });
        panel2.add(btnFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 292, 80, 30));

        jButton5.setBackground(new java.awt.Color(255, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Tutup");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 17, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenghuniActionPerformed
        // TODO add your handling code here:
            String namaFile;
            HashMap hash = new HashMap();
                namaFile = "/reports/Laporan_Penghuni1.jasper";
//                hash.put("id_transaksi",id_transaksi);
            
            CetakLaporan(namaFile, hash);
        
    }//GEN-LAST:event_btnPenghuniActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        // TODO add your handling code here:
        String namaFile;
            HashMap hash = new HashMap();
                namaFile = "/reports/LaporanKamar.jasper";            
            CetakLaporan(namaFile, hash);
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFasilitasActionPerformed
        // TODO add your handling code here:
        String namaFile;
            HashMap hash = new HashMap();
                namaFile = "/reports/LaporanFasilitas.jasper";            
            CetakLaporan(namaFile, hash);
    }//GEN-LAST:event_btnFasilitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFasilitas;
    private javax.swing.JButton btnKamar;
    private javax.swing.JButton btnPenghuni;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private usu.widget.Panel panel1;
    private usu.widget.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
