/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class frm_Fasilitas extends javax.swing.JFrame {

    /**
     * Creates new form frm_Fasilitas
     */
    public frm_Fasilitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutStyle1 = new org.jdesktop.layout.LayoutStyle();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jPanel1 = new javax.swing.JPanel();
        btnSimpanFasilitas = new javax.swing.JButton();
        btnTambahFasilitas = new javax.swing.JButton();
        btnEditFasilitas = new javax.swing.JButton();
        btnHapusFasilitas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFasilitas = new javax.swing.JTable();
        btnTutupFasilitas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfNomorFasilitas = new javax.swing.JTextField();
        tfNamaFasilitas = new javax.swing.JTextField();
        tfHargaFasilitas = new javax.swing.JTextField();
        tfStatusFasilitas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbFilterFasilitas = new javax.swing.JComboBox();
        btnCariFasilitas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfCariFasilitas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/IMG/bgFormFasilitas.png"))); // NOI18N
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnSimpanFasilitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpanFasilitas.setText("SIMPAN");
        btnSimpanFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanFasilitasActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpanFasilitas);

        btnTambahFasilitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambahFasilitas.setText("TAMBAH");
        jPanel1.add(btnTambahFasilitas);

        btnEditFasilitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditFasilitas.setText("EDIT");
        jPanel1.add(btnEditFasilitas);

        btnHapusFasilitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapusFasilitas.setText("HAPUS");
        jPanel1.add(btnHapusFasilitas);

        panelGlass1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 294, 362, 50));

        tblFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFasilitas);

        panelGlass1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 710, 380));

        btnTutupFasilitas.setBackground(new java.awt.Color(240, 217, 39));
        btnTutupFasilitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTutupFasilitas.setText("Tutup");
        btnTutupFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutupFasilitasMouseClicked(evt);
            }
        });
        btnTutupFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupFasilitasActionPerformed(evt);
            }
        });
        panelGlass1.add(btnTutupFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 100, 40));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 4));

        tfNomorFasilitas.setText("jTextField1");
        jPanel2.add(tfNomorFasilitas);

        tfNamaFasilitas.setText("jTextField2");
        jPanel2.add(tfNamaFasilitas);

        tfHargaFasilitas.setText("jTextField3");
        tfHargaFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaFasilitasActionPerformed(evt);
            }
        });
        jPanel2.add(tfHargaFasilitas);

        tfStatusFasilitas.setText("jTextField4");
        jPanel2.add(tfStatusFasilitas);

        panelGlass1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 120));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        cbFilterFasilitas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Berdasarkan", "Harga", "Nama", "Status" }));
        jPanel3.add(cbFilterFasilitas);

        btnCariFasilitas.setText("CARI");
        jPanel3.add(btnCariFasilitas);

        panelGlass1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 280, 30));

        jPanel4.setLayout(new java.awt.BorderLayout());

        tfCariFasilitas.setText("jTextField5");
        tfCariFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariFasilitasActionPerformed(evt);
            }
        });
        jPanel4.add(tfCariFasilitas, java.awt.BorderLayout.CENTER);

        panelGlass1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 230, 30));

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1190, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanFasilitasActionPerformed

    private void tfHargaFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaFasilitasActionPerformed

    private void btnTutupFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupFasilitasActionPerformed

    private void btnTutupFasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutupFasilitasMouseClicked
        // TODO add your handling code here:
//         int pilihan = JOptionPane.showConfirmDialog(this,"Apa anda yakin ingin Keluar","Exit",JOptionPane.YES_NO_OPTION);
//        if (pilihan==0) {
//            System.exit(0);
//        }    
        dispose();
    }//GEN-LAST:event_btnTutupFasilitasMouseClicked

    private void tfCariFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariFasilitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Fasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Fasilitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariFasilitas;
    private javax.swing.JButton btnEditFasilitas;
    private javax.swing.JButton btnHapusFasilitas;
    private javax.swing.JButton btnSimpanFasilitas;
    private javax.swing.JButton btnTambahFasilitas;
    private javax.swing.JButton btnTutupFasilitas;
    private javax.swing.JComboBox cbFilterFasilitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.layout.LayoutStyle layoutStyle1;
    private usu.widget.glass.PanelGlass panelGlass1;
    private javax.swing.JTable tblFasilitas;
    private javax.swing.JTextField tfCariFasilitas;
    private javax.swing.JTextField tfHargaFasilitas;
    private javax.swing.JTextField tfNamaFasilitas;
    private javax.swing.JTextField tfNomorFasilitas;
    private javax.swing.JTextField tfStatusFasilitas;
    // End of variables declaration//GEN-END:variables
}
