/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Class.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author acer
 */
public class frm_PilihFasilitas extends javax.swing.JFrame {
private Connection con = koneksi.getConnection();
    private Statement stt;
    private ResultSet rss;
    int a,b,c,d,e,jumlah;
    
    public void combo_fasilitas(){
        try{
        String sql = "Select nama_fasilitas from fasilitas";
        stt = con.createStatement();
        rss = stt.executeQuery(sql);
        while(rss.next()){
            cbF1.addItem(rss.getString("nama_fasilitas"));
            cbF2.addItem(rss.getString("nama_fasilitas"));
            cbF3.addItem(rss.getString("nama_fasilitas"));
            cbF4.addItem(rss.getString("nama_fasilitas"));
            cbF5.addItem(rss.getString("nama_fasilitas"));
        }
        }catch(SQLException e){
            
        }
    }
    /**
     * Creates new form frm_PilihFasilitas
     */
    public frm_PilihFasilitas() {
        initComponents();
        combo_fasilitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new usu.widget.Panel();
        cbF1 = new javax.swing.JComboBox<>();
        cbF2 = new javax.swing.JComboBox<>();
        cbF4 = new javax.swing.JComboBox<>();
        cbF3 = new javax.swing.JComboBox<>();
        cbF5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbF1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cbF1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbF1ItemStateChanged(evt);
            }
        });

        cbF2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cbF2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbF2ItemStateChanged(evt);
            }
        });

        cbF4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cbF4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbF4ItemStateChanged(evt);
            }
        });

        cbF3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cbF3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbF3ItemStateChanged(evt);
            }
        });

        cbF5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cbF5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbF5ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Fasilitas 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fasilitas 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fasilitas 3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fasilitas 4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Fasilitas 5");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Tambah Fasilitas");

        jLabel7.setText("Jumlah Rp");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(77, 77, 77))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbF2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbF3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbF4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbF5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(cbF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(cbF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbF1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbF1ItemStateChanged
        // TODO add your handling code here:
        if(cbF1.getSelectedItem().equals("none")){
            a = 0;
            jumlah = a + b + c + d + e;
            String jmb = String.valueOf(jumlah);
            tfJumlah.setText(jmb);
            
        }
        else{
            try
                {
                    String sql="select harga_fasilitas from fasilitas where nama_fasilitas='"+cbF1.getSelectedItem()+"';";
                    stt = con.createStatement();
                    rss = stt.executeQuery(sql);

                    while(rss.next())
                    {
                        int harga = Integer.parseInt(rss.getString("harga_fasilitas"));    
                        a = harga;
                        jumlah = a + b + c + d + e;

                    }
                    String jmb = String.valueOf(jumlah);
                        tfJumlah.setText(jmb);
                        


                }catch(Exception e)
                {
    //                JOptionPane.showMessageDialog(null,"GAGAL");
                } 
        }
    }//GEN-LAST:event_cbF1ItemStateChanged

    private void cbF2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbF2ItemStateChanged
        // TODO add your handling code here:
        if(cbF2.getSelectedItem().equals("none")){
            b = 0;
            jumlah = a + b + c + d + e;
            String jmb = String.valueOf(jumlah);
            tfJumlah.setText(jmb);
            
        }
        else{
            try
                {
                    String sql="select harga_fasilitas from fasilitas where nama_fasilitas='"+cbF2.getSelectedItem()+"';";
                    stt = con.createStatement();
                    rss = stt.executeQuery(sql);

                    while(rss.next())
                    {
                        int harga = Integer.parseInt(rss.getString("harga_fasilitas"));    

                        b = harga;
                        jumlah = a + b + c + d + e;

                    }
                    String jmb = String.valueOf(jumlah);
                        tfJumlah.setText(jmb);
                        


                }catch(Exception e)
                {
    //                JOptionPane.showMessageDialog(null,"GAGAL");
                } 
        }
    }//GEN-LAST:event_cbF2ItemStateChanged

    private void cbF3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbF3ItemStateChanged
        // TODO add your handling code here:
        if(cbF3.getSelectedItem().equals("none")){
            c = 0;
            jumlah = a + b + c + d + e;
            String jmb = String.valueOf(jumlah);
            tfJumlah.setText(jmb);
            
        }
        else{
            try
                {
                    String sql="select harga_fasilitas from fasilitas where nama_fasilitas='"+cbF3.getSelectedItem()+"';";
                    stt = con.createStatement();
                    rss = stt.executeQuery(sql);

                    while(rss.next())
                    {
                        int harga = Integer.parseInt(rss.getString("harga_fasilitas"));    
                        c = harga;
                        jumlah = a + b + c + d + e;

                    }
                    String jmb = String.valueOf(jumlah);
                        tfJumlah.setText(jmb);
                        


                }catch(Exception e)
                {
    //                JOptionPane.showMessageDialog(null,"GAGAL");
                } 
        }
    }//GEN-LAST:event_cbF3ItemStateChanged

    private void cbF4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbF4ItemStateChanged
        // TODO add your handling code here:
        if(cbF4.getSelectedItem().equals("none")){
            d = 0;
            jumlah = a + b + c + d + e;
            String jmb = String.valueOf(jumlah);
            tfJumlah.setText(jmb);
            
        }
        else{
            try
                {
                    String sql="select harga_fasilitas from fasilitas where nama_fasilitas='"+cbF4.getSelectedItem()+"';";
                    stt = con.createStatement();
                    rss = stt.executeQuery(sql);

                    while(rss.next())
                    {
                        int harga = Integer.parseInt(rss.getString("harga_fasilitas"));    
                        d = harga;
                        jumlah = a + b + c + d + e;

                    }
                    String jmb = String.valueOf(jumlah);
                        tfJumlah.setText(jmb);
                        

                }catch(Exception e)
                {
    //                JOptionPane.showMessageDialog(null,"GAGAL");
                } 
        }
    }//GEN-LAST:event_cbF4ItemStateChanged

    private void cbF5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbF5ItemStateChanged
        // TODO add your handling code here:
        if(cbF5.getSelectedItem().equals("none")){
            e = 0;
            jumlah = a + b + c + d + e;
            String jmb = String.valueOf(jumlah);
            tfJumlah.setText(jmb);
            
        }
        else{
            try
            {
                String sql="select harga_fasilitas from fasilitas where nama_fasilitas='"+cbF5.getSelectedItem()+"';";
                stt = con.createStatement();
                rss = stt.executeQuery(sql);

                while(rss.next())
                {
                    int harga = Integer.parseInt(rss.getString("harga_fasilitas"));    
                    e = harga;
                    jumlah = a + b + c + d + e;
                    
                }
                String jmb = String.valueOf(jumlah);
                    tfJumlah.setText(jmb);
                    
                
                
            }catch(Exception e)
            {
//                JOptionPane.showMessageDialog(null,"GAGAL");
            } 
        }
    }//GEN-LAST:event_cbF5ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        frm_transaksi trans = new frm_transaksi();
        
        frm_transaksi.jumlahfasilitas = Integer.parseInt(tfJumlah.getText());
        frm_transaksi.tfJumlahFas.setText(tfJumlah.getText());        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_PilihFasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_PilihFasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_PilihFasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_PilihFasilitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_PilihFasilitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbF1;
    private javax.swing.JComboBox<String> cbF2;
    private javax.swing.JComboBox<String> cbF3;
    private javax.swing.JComboBox<String> cbF4;
    private javax.swing.JComboBox<String> cbF5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private usu.widget.Panel panel1;
    private javax.swing.JTextField tfJumlah;
    // End of variables declaration//GEN-END:variables
}
