/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class frm_transaksi extends javax.swing.JFrame {

    /**
     * Creates new form frm_transaksi
     */
    public frm_transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutStyle1 = new org.jdesktop.layout.LayoutStyle();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jPanel4 = new javax.swing.JPanel();
        btnSimpanTransaksi = new javax.swing.JButton();
        btnTambahTransaksi = new javax.swing.JButton();
        btnEditTransaksi = new javax.swing.JButton();
        btnHapusTransaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnCetakKwitansi = new javax.swing.JButton();
        btnTutupPembayaran = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tfNoPembayaran = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tfKodePenghuni = new javax.swing.JTextField();
        btnCariKodePenghuni = new javax.swing.JButton();
        tfNamaPenghuni = new javax.swing.JTextField();
        tfNomorKtpPenghuni = new javax.swing.JTextField();
        tfAlamatAsalPenghuni = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tfPilihKamarPenghuni = new javax.swing.JTextField();
        btnCariKamarPenghuni = new javax.swing.JButton();
        tfNamaKamar = new javax.swing.JTextField();
        tfHargaKamar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tfPeriode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        tfTerbilang = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        tfCariPembayaran = new javax.swing.JTextField();
        cbFilterPembayaran = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        btnCariKamar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        dcTglMasuk = new com.toedter.calendar.JDateChooser();
        dcTglKeluar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/IMG/bgFormPembayaran.png"))); // NOI18N
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        btnSimpanTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpanTransaksi.setText("SIMPAN");
        jPanel4.add(btnSimpanTransaksi);

        btnTambahTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTambahTransaksi.setText("TAMBAH");
        btnTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTransaksiActionPerformed(evt);
            }
        });
        jPanel4.add(btnTambahTransaksi);

        btnEditTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditTransaksi.setText("EDIT");
        btnEditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTransaksiActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditTransaksi);

        btnHapusTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapusTransaksi.setText("HAPUS");
        jPanel4.add(btnHapusTransaksi);

        panelGlass1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 460, 50));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        panelGlass1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 590, 390));

        btnCetakKwitansi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCetakKwitansi.setText("KWITANSI PEMBAYARAN");
        panelGlass1.add(btnCetakKwitansi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, 170, 70));

        btnTutupPembayaran.setBackground(new java.awt.Color(240, 177, 32));
        btnTutupPembayaran.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTutupPembayaran.setText("Tutup");
        btnTutupPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutupPembayaranMouseClicked(evt);
            }
        });
        btnTutupPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupPembayaranActionPerformed(evt);
            }
        });
        panelGlass1.add(btnTutupPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 100, 30));

        jPanel5.setLayout(new java.awt.GridLayout(10, 0, 0, 4));

        tfNoPembayaran.setText("jTextField1");
        jPanel5.add(tfNoPembayaran);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        tfKodePenghuni.setText("jTextField2");
        jPanel1.add(tfKodePenghuni);

        btnCariKodePenghuni.setText("CARI");
        btnCariKodePenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKodePenghuniActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariKodePenghuni);

        jPanel5.add(jPanel1);

        tfNamaPenghuni.setText("jTextField3");
        jPanel5.add(tfNamaPenghuni);

        tfNomorKtpPenghuni.setText("jTextField4");
        jPanel5.add(tfNomorKtpPenghuni);

        tfAlamatAsalPenghuni.setText("jTextField5");
        jPanel5.add(tfAlamatAsalPenghuni);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        tfPilihKamarPenghuni.setText("jTextField6");
        jPanel2.add(tfPilihKamarPenghuni);

        btnCariKamarPenghuni.setText("CARI");
        jPanel2.add(btnCariKamarPenghuni);

        jPanel5.add(jPanel2);

        tfNamaKamar.setText("jTextField7");
        jPanel5.add(tfNamaKamar);

        tfHargaKamar.setText("jTextField8");
        jPanel5.add(tfHargaKamar);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 4, 0));

        tfPeriode.setText("jTextField9");
        jPanel3.add(tfPeriode);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bulan");
        jPanel3.add(jLabel1);

        jPanel5.add(jPanel3);

        tfTotal.setText("jTextField10");
        jPanel5.add(tfTotal);

        panelGlass1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 290, 310));

        tfTerbilang.setText("jTextField11");
        panelGlass1.add(tfTerbilang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 470, 30));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        tfCariPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariPembayaranActionPerformed(evt);
            }
        });
        jPanel6.add(tfCariPembayaran);

        cbFilterPembayaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Berdasarkan", "Kode Penghuni", "No. KTP", "Nama Kamar" }));
        jPanel6.add(cbFilterPembayaran);

        panelGlass1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 240, 60));

        jPanel7.setLayout(new java.awt.BorderLayout());

        btnCariKamar.setText("CARI");
        jPanel7.add(btnCariKamar, java.awt.BorderLayout.CENTER);

        panelGlass1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 80, 30));

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 4));
        jPanel8.add(dcTglMasuk);
        jPanel8.add(dcTglKeluar);

        panelGlass1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 463, 285, 54));

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1180, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditTransaksiActionPerformed

    private void btnTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahTransaksiActionPerformed

    private void btnTutupPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupPembayaranActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTutupPembayaranActionPerformed

    private void btnTutupPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutupPembayaranMouseClicked
        // TODO add your handling code here:
//         int pilihan = JOptionPane.showConfirmDialog(this,"Apa anda yakin ingin Keluar","Exit",JOptionPane.YES_NO_OPTION);
//        if (pilihan==0) {
//            System.exit(0);
//        }
        dispose();
    }//GEN-LAST:event_btnTutupPembayaranMouseClicked

    private void btnCariKodePenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKodePenghuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariKodePenghuniActionPerformed

    private void tfCariPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariKamar;
    private javax.swing.JButton btnCariKamarPenghuni;
    private javax.swing.JButton btnCariKodePenghuni;
    private javax.swing.JButton btnCetakKwitansi;
    private javax.swing.JButton btnEditTransaksi;
    private javax.swing.JButton btnHapusTransaksi;
    private javax.swing.JButton btnSimpanTransaksi;
    private javax.swing.JButton btnTambahTransaksi;
    private javax.swing.JButton btnTutupPembayaran;
    private javax.swing.JComboBox cbFilterPembayaran;
    private com.toedter.calendar.JDateChooser dcTglKeluar;
    private com.toedter.calendar.JDateChooser dcTglMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.layout.LayoutStyle layoutStyle1;
    private usu.widget.glass.PanelGlass panelGlass1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField tfAlamatAsalPenghuni;
    private javax.swing.JTextField tfCariPembayaran;
    private javax.swing.JTextField tfHargaKamar;
    private javax.swing.JTextField tfKodePenghuni;
    private javax.swing.JTextField tfNamaKamar;
    private javax.swing.JTextField tfNamaPenghuni;
    private javax.swing.JTextField tfNoPembayaran;
    private javax.swing.JTextField tfNomorKtpPenghuni;
    private javax.swing.JTextField tfPeriode;
    private javax.swing.JTextField tfPilihKamarPenghuni;
    private javax.swing.JTextField tfTerbilang;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
